#!perl

# DATE
# VERSION

# FRAGMENT id=shcompgen-hint completer=1 for=meta

use strict;
use warnings;

use Shell::Completer;

declare_completer(
    options => {
        'help' => undef,
        'whitespace|ws' => undef,
        'version' => undef,
        'themes' => undef,
        'remote' => undef,
        'check' => undef,
        'category=s' => sub {
            require Complete::Acme::MetaSyntactic;

            my %args = @_;
            my $word = $args{word};

            my $theme = $args{words}[0];
            Complete::Acme::MetaSyntactic::complete_meta_category(
                word => $word, theme => $theme);
        },
        'sources' => undef,
        '<>' => sub {
            require Complete::Acme::MetaSyntactic;

            my %args = @_;
            my $word = $args{word};

            if ($args{type} eq 'arg') {
                if ($args{argpos} == 0) {
                    return Complete::Acme::MetaSyntactic::complete_meta_theme_and_category(
                        word => $word);
                } elsif ($args{argpos} == 1) {
                    require Complete::Number;
                    return Complete::Number::complete_int(
                        word => $word,
                        min => 1,
                    );
                }
                undef;
            }
            undef;
        },
    },
);

# ABSTRACT: Shell completer for meta (Acme::MetaSyntactic CLI)
# PODNAME:

=head1 SYNOPSIS

To install, install this module and then in your bash (and/or bash startup
file):

 complete -C _meta meta

or, you can use L<shcompgen> to do that for you automatically.

Now L<meta> has bash completion:

 % meta -<tab>                 ;# complete list of options
 % meta <tab>                  ;# complete theme
 % meta christmas --cat <tab>  ;# complete category
